name = "Section_8_1_Submodules"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[[executable]]
name="Section_8_1_Submodule"
source-dir="app"
main="section_8_1_submodule.f90"
