name = "Section_9_3_SOS_Difference"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[[executable]]
name="Section_9_3_SOS_Difference"
source-dir="app"
main="section_9_3_sos_difference.f90"
