name = "Section_Arrays_Compute_Factorial"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[[executable]]
name="Section_Arrays_Compute_Factorial"
source-dir="app"
main="section_arrays_compute_factorial.f90"
