name = "Section_Implicit_vs_Explicit_Loops"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[[executable]]
name="Section_Implicit_vs_Explicit_Loops"
source-dir="app"
main="section_implicit_vs_explicit_loops.f90"
