name = "Section_Computing_Pi_Compute_Pi"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[[executable]]
name="Section_Computing_Pi_Compute_Pi"
source-dir="app"
main="section_computing_pi_compute_pi.f90"
