name = "Section_BLAS_LAPACK_SV"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
link = ["blas", "lapack"]

[install]
library = false

[[executable]]
name="Section_BLAS_LAPACK_SV"
source-dir="app"
main="section_blas_lapack_sv.f90"
