name = "Section_Arrays_Array_Timing"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[[executable]]
name="Section_Arrays_Array_Timing"
source-dir="app"
main="section_arrays_array_timing.f90"
