name = "Section_8_2_Time_Matrix_Multiply"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[[executable]]
name="Section_8_2_Time_Matrix_Multiply"
source-dir="app"
main="section_8_2_time_matrix_multiply.f90"
