name = "Section_Arrays_Assumed"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[[executable]]
name="Section_Arrays_Assumed"
source-dir="app"
main="section_arrays_assumed.f90"
