name = "Section_Arrays_Matrix"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[[executable]]
name="Section_Arrays_Matrix"
source-dir="app"
main="section_arrays_matrix.f90"