name = "Section_Arrays_Array_Initialization"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[[executable]]
name="Section_Arrays_Array_Initialization"
source-dir="app"
main="section_arrays_array_initialization.f90"
