name = "Cold_Front_Calculator_with_Loop"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[[executable]]
name="Cold_Front_Calculator_with_Loop"
source-dir="app"
main="cold_front_calculator_with_loop.f90"
