name = "Section_Call_By_Semantics_Call_By_Value"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[[executable]]
name="Section_Call_By_Semantics_Call_By_Value"
source-dir="app"
main="section_call_by_semantics_call_by_value.f90"
