name = "Section_Arrays_Normalize"
version = "0.1.0"
license = "license"
author = "Mark Khusid"
maintainer = "markkhusid@protonmail.com"
copyright = "Copyright 2022, Mark Khusid"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
