name = "Analyzing_Time_Series_Data_with_Arrays"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[[executable]]
name="Stock_Gain"
source-dir="app"
main="stock_gain.f90"
