name = "Section_Ball_Throw"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[[executable]]
name="Section_Ball_Throw"
source-dir="app"
main="section_ball_throw.F90"
