name = "Section_Arrays_Reshape"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[[executable]]
name="Section_Arrays_Reshape"
source-dir="app"
main="section_arrays_reshape.f90"
