name = "Section_Arrays_Identity"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[[executable]]
name="Section_Arrays_Identity"
source-dir="app"
main="section_arrays_identity.f90"

